### ISSUE TITLE
회원가입 안 됨 - (서비스 이용약관 동의 - 예상되지 않은 오류 발생. 다시 시도) - (gp_07에서는 정상 가입 가능)

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#198]
1. 화면 위치
: 회원 가입 시

2. 증상
; 회원가입 안 됨. **(gp_08)**
  (서비스 이용약관 동의 중 - 예상되지 않은 오류가 발생했습니다. 다시 시도해보세요.)
  
   **(gp_07에서는 정상 가입 가능)**

3. 개선
: 회원가입 정상 기능

4. 영상 첨부
 (comment에 추가)

**Comment by doidoit** [comment]
https://user-images.githubusercontent.com/98443099/184840257-a151fcc0-6b7c-42a9-810b-758794d29efa.mp4
qa

**Comment by yun-gitple** [comment]
telecom관련해서 front-end, back-end간에 sync가 안맞은것 같습니다.
저는 재현은 안되는데 (22/08/16, 20시 가량) 일시적인 문제인지 확인이 필요해 보이네요. 
```
"message": [
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:           "telecom should not be empty",
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:           "telecom must be a string"
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:         ],
```

### 전체 로그

```
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]: [2022-08-16 09:23:40.520] INFO:  - incoming request
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:     req: {
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:       "method": "POST",
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:       "url": "/api/v1/accounts/signup",
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:       "hostname": "app.betterday.co.kr",
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:       "remoteAddress": "10.0.0.7",
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:       "remotePort": 34920
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:     }
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:     reqId: "req-a"
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]: [2022-08-16 09:23:40.530] INFO:  - request completed
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:     res: {
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:       "statusCode": 400
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:     }
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:     responseTime: 10.26163101196289
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:     reqId: "req-a"
Aug 16 09:23:40 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.imeritz.com/v1/invest/accounts/transactions
Aug 16 09:23:40 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://myinfo.kiwoom.com:3443/v1/invest/accounts/transactions
Aug 16 09:23:40 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://openapi-mydata.kftc.or.kr/v1/bank/accounts/loan/transactions
Aug 16 09:23:40 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://myinfo.kiwoom.com:3443/v1/invest/accounts/transactions
Aug 16 09:23:40 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.imeritz.com/v1/invest/accounts/products
Aug 16 09:23:40 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.imeritz.com/v1/invest/accounts/basic
Aug 16 09:23:40 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://openapi-mydata.kftc.or.kr/v1/bank/accounts/loan/transactions
Aug 16 09:23:41 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.shinhaninvest.com:8443/v1/invest/accounts/transactions
Aug 16 09:23:41 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.imeritz.com/v1/invest/accounts/products
Aug 16 09:23:41 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.shinhaninvest.com:8443/v1/invest/accounts/basic
Aug 16 09:23:41 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://openapi-mydata.kftc.or.kr/v1/bank/accounts/loan/transactions
Aug 16 09:23:41 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.imeritz.com/v1/invest/accounts/transactions
Aug 16 09:23:41 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.imeritz.com/v1/invest/accounts/products
Aug 16 09:23:41 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.shinhaninvest.com:8443/v1/invest/accounts/basic
Aug 16 09:23:41 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.shinhaninvest.com:8443/v1/invest/accounts/transactions
@@@
/09:23:40.530
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:     req: {
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]: [2022-08-16 09:23:40.530] INFO:  - request completed
Aug 16 09:23:40 prd-gw2 main-prd-gw2.2[20065]:     reqId: "req-a"
Aug 16 09:23:40 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.imeritz.com/v1/invest/accounts/transactions
Aug 16 09:23:40 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://myinfo.kiwoom.com:3443/v1/invest/accounts/transactions
Aug 16 09:23:40 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://openapi-mydata.kftc.or.kr/v1/bank/accounts/loan/transactions
Aug 16 09:23:40 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://myinfo.kiwoom.com:3443/v1/invest/accounts/transactions
Aug 16 09:23:40 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.imeritz.com/v1/invest/accounts/products
Aug 16 09:23:40 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.imeritz.com/v1/invest/accounts/basic
Aug 16 09:23:40 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://openapi-mydata.kftc.or.kr/v1/bank/accounts/loan/transactions
Aug 16 09:23:41 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.shinhaninvest.com:8443/v1/invest/accounts/transactions
Aug 16 09:23:41 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.imeritz.com/v1/invest/accounts/products
Aug 16 09:23:41 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.shinhaninvest.com:8443/v1/invest/accounts/basic
Aug 16 09:23:41 prd-gw2 turple_dmz_proxy-prd-gw2.2[20065]: POST https://mydata.shinhaninvest.com:8443/v1/invest/accounts/transactions
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]: [2022-08-16 09:23:40.530] #033[31mERROR#033[39m: #033[36mHttpExceptionFilter - resp={"status_code":400,"message":"Bad Request Exception","timestamp":"2022-08-16T09:23:40.530Z","path":"/api/v1/accounts/signup","resp_msg":"Bad Request Exception"}#033[39m
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:     err: {
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:       "type": "BadRequestException",
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:       "message": "Bad Request Exception",
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:       "stack":
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:           BadRequestException: Bad Request Exception
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:               at ValidationPipe.exceptionFactory (/app/node_modules/@nestjs/common/pipes/validation.pipe.js:89:20)
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:               at ValidationPipe.transform (/app/node_modules/@nestjs/common/pipes/validation.pipe.js:65:30)
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:               at processTicksAndRejections (internal/process/task_queues.js:95:5)
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:               at async resolveParamValue (/app/node_modules/@nestjs/core/router/router-execution-context.js:147:23)
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:               at async Promise.all (index 0)
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:               at async pipesFn (/app/node_modules/@nestjs/core/router/router-execution-context.js:150:13)
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:               at async /app/node_modules/@nestjs/core/router/router-execution-context.js:37:30
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:       "response": {
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:         "statusCode": 400,
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:         "message": [
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:           "telecom should not be empty",
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:           "telecom must be a string"
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:         ],
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:         "error": "Bad Request"
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:       },
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:       "status": 400,
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:       "name": "BadRequestException"
Aug 16 09:23:41 prd-gw2 main-prd-gw2.2[20065]:     }
```

**Comment by doidoit** [comment]
현재 재현 안 됨 > closed
